### ISSUE TITLE
Renderer for items in RadioButtonGroup

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/vaadin-radio-button-flow#10]
Part of the #4.

It should be possible to for customize the items content as components using a Renderer that allows returning components that will be put inside the `vaadin-radio-button`

**Comment by Legioth** [comment]
I wouldn't use the term "Renderer" here since it's technically different than what's used with e.g. `Grid`.
* In the radio button group case, the component instances can be directly put into the regular server-side DOM
* The actual `Renderer` concept is a way of managing the contents of `<template>` elements in the DOM and what happens when actual instances of that template are stamped out by code that is outside our control.

**Comment by Legioth** [comment]
On the other hand, we might also consider moving complexity into the `Renderer` interface and instead expose exactly the same API for application developers. This would indeed require each `Renderer` implementation to support two different modes depending on what kind of component it's used with, but that's probably an acceptable tradeoff since the flexibility of the existing `TemplateRenderer` and `ComponentRenderer` classes mean it's never really necessary to create new classes.

**Comment by denis-anisimov** [comment]
Just to clarify the ticket:
- There is already a ticket about `IconGenerator`.
- "Icon" is a slot for "label" component which is set _before_ the `vaadin-radio-button` content.
- So this ticket is kind of covered by the `IconGenerator` (because you already can set the component inside `vaadin-radio-button`). The only difference is that the content stays always there.
- This ticket is just a way to set a component as the content of the `vaadin-radio-button` component (at the moment we set only text there).

The resulting API becomes very confusing for me:
- `IconGenerator`  which already covers some kind of renderer functionality
- `ItemLabelProvider` which is intended to work when text is used as a content (which overlaps with renderer functionality)
- `Renderer` : renderer overrides `ItemLabelProvider` functionality. In reality `ItemLabelProvider` is just another view of renderer. It renders component as a text with the required text representation.

Two last items here are strongly connected. If `renderer` is set then it cancels the `ItemLabelProvider` (since it replaces the content). That's confusing.
But what even more confusing: what happens if there is active `renderer` and I set a new `ItemLabelProvider`? Will it cancel the `renderer`? Or it's no op ?

Looks like `ItemLabelProvider` should be removed completely and there should be a dedicated `renderer` which replaces `ItemLabelProvider` functionality. So there will be only one getter/setter for renderer without confusion.
But then it won't be so obvious how to set equivalent of `ItemLabelProvider`.

**Comment by pleku** [comment]
Yes I agree, after thinking on how this could affect `Grid` and `ComboBox` too.

Thus there would just be `setRenderer(Renderer renderer)` for all of the components, and depending on the component it should technically support the template and non-template usage (eg. grid vs radiobuttongroup).

Thus this could mean that
- `ItemLabelProvider` -> ` `TextRenderer`
- `IconGenerator` need to figure out what to do with this, basically the user should be really easily just returning icon + text, but mayhaps it is just enough to showcase this with the `ComponentRenderer`

**Comment by Legioth** [comment]
One option could be to have three methods:
```
setRenderer(Renderer<V> renderer);
setRenderer(ValueProvider<V, String> labelProvider);
setRenderer(ValueProvider<V, String> labelProvider, ValueProvider<V, Component> iconProvider);
```

**Comment by denis-anisimov** [comment]
Several methods is always a logical problem: they cancel each other which is not obvious.

**Comment by Legioth** [comment]
Methods with the same name are expected to cancel each other, but methods with distinct names are expected to be independent of each other.
