### ISSUE TITLE
Making an item disabled doesn't disable the communication with the server

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/vaadin-radio-button-flow#47]
Here is a gif showcasing the problem. The item is only disabled on the client-side, not on the server-side, and events can still be triggered for the disabled value:

![group_bug](https://user-images.githubusercontent.com/7464735/39049197-30c89120-44a9-11e8-9921-ece7dfad88cd.gif)

The code to simulate the problem:
```java
Div valueInfo = new Div();

RadioButtonGroup<String> group = new RadioButtonGroup<>();
group.setItems("foo", "bar", "baz");
group.setItemEnabledProvider(item -> !"bar".equals(item));

group.addValueChangeListener(
                event -> valueInfo.setText(group.getValue()));
```

**Comment by denis-anisimov** [comment]
I'm not sure whether this issue is valid at all.
It's a mixture of `RadioButtonGroup` and `RadioButton`.
`ItemEnabledProvider` disables the button not a group.
So since the group is not disabled it's possible to update it's value.......

Well, this observation from the point of view of web components.

On the other hand is we consider Java API then may be it has sense since we don't care about the resulting web component structure.....

**Comment by denis-anisimov** [comment]
More observations if we decide that this is really a bug:
- It's not clear how to fix this properly at all: client side doesn't consider change to the disabled button as impossible. Then it sends the value from the client side to the server side (and we can't do anything here with this). So it's already changed on the client side. Now the only thing we may do is: get ths change on the server and revert it back _FROM THE SERVER SIDE_. This is kind of ugly.
- If this is an issue then it should be fixed by the web component I think.
- Otherwise we will need to do it as I've already described above via server-side round-trip which is not a proper fix.

**Comment by caalador** [comment]
Only fix I can see for this is the suggested revert of the disabled selection on the server side if the disabled item is selected.
